import JSZip from 'jszip'

/*
 * Simulated response engine for the hosted showcase.
 * The real VibeAI API is a code-execution surface and binds to localhost
 * only — so the public site ships with this stand-in. Point `respond` at
 * the FastAPI server (REST/WebSocket) to go live on a trusted machine.
 */

const CODING_HINTS = [
  'code', 'build', 'create', 'script', 'function', 'class', 'bug', 'fix',
  'python', 'javascript', 'react', 'html', 'css', 'api', 'app', 'website',
  'cli', 'program', 'refactor', 'implement', 'landing page', 'server',
]

export function isCodingTask(text) {
  const t = text.toLowerCase()
  return CODING_HINTS.some((h) => t.includes(h))
}

function slugify(text) {
  let slug = text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
  if (slug.length > 32) {
    slug = slug.slice(0, 32)
    // don't cut mid-word
    const cut = slug.lastIndexOf('-')
    if (cut > 12) slug = slug.slice(0, cut)
  }
  return slug || 'vibeai-project'
}

function pythonProject(prompt, slug) {
  return [
    {
      path: 'main.py',
      content: `"""${slug} — generated by VibeAI (demo engine).\n\nTask: ${prompt.trim()}\n"""\n\nimport argparse\n\n\ndef run(name: str) -> str:\n    return f"VibeAI demo scaffold ready, {name}."\n\n\ndef main() -> None:\n    parser = argparse.ArgumentParser(description=__doc__)\n    parser.add_argument("--name", default="world")\n    args = parser.parse_args()\n    print(run(args.name))\n\n\nif __name__ == "__main__":\n    main()\n`,
    },
    {
      path: 'test_main.py',
      content: `from main import run\n\n\ndef test_run():\n    assert "ready" in run("test")\n`,
    },
    {
      path: 'requirements.txt',
      content: '# no third-party dependencies for the scaffold\n',
    },
    {
      path: 'README.md',
      content: `# ${slug}\n\nGenerated by VibeAI's demo engine for the task:\n\n> ${prompt.trim()}\n\n## Run\n\n\`\`\`bash\npython main.py --name you\n\`\`\`\n\n## Test\n\n\`\`\`bash\npython -m pytest -q\n\`\`\`\n`,
    },
  ]
}

function webProject(prompt, slug) {
  return [
    {
      path: 'index.html',
      content: `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${slug}</title>\n    <link rel="stylesheet" href="styles.css" />\n  </head>\n  <body>\n    <main class="card">\n      <h1>${slug}</h1>\n      <p>Scaffold generated by VibeAI for: ${prompt.trim()}</p>\n      <button id="cta">It works</button>\n    </main>\n    <script src="app.js"></script>\n  </body>\n</html>\n`,
    },
    {
      path: 'styles.css',
      content: `:root {\n  --bg: #05070a;\n  --accent: #2be8ff;\n}\n\nbody {\n  margin: 0;\n  min-height: 100vh;\n  display: grid;\n  place-items: center;\n  background: var(--bg);\n  color: #d9f6fb;\n  font-family: system-ui, sans-serif;\n}\n\n.card {\n  text-align: center;\n  padding: 3rem;\n  border: 1px solid rgba(43, 232, 255, 0.25);\n  border-radius: 8px;\n}\n\nbutton {\n  margin-top: 1rem;\n  padding: 0.6rem 1.4rem;\n  background: var(--accent);\n  border: none;\n  border-radius: 4px;\n  font-weight: 600;\n  cursor: pointer;\n}\n`,
    },
    {
      path: 'app.js',
      content: `document.getElementById('cta').addEventListener('click', () => {\n  alert('VibeAI scaffold running.')\n})\n`,
    },
    {
      path: 'README.md',
      content: `# ${slug}\n\nGenerated by VibeAI's demo engine for the task:\n\n> ${prompt.trim()}\n\nOpen \`index.html\` in a browser.\n`,
    },
  ]
}

export function generateFiles(prompt) {
  const t = prompt.toLowerCase()
  const slug = slugify(prompt)
  const isWeb = ['html', 'css', 'website', 'landing', 'page', 'react', 'frontend'].some((h) =>
    t.includes(h),
  )
  return { slug, files: isWeb ? webProject(prompt, slug) : pythonProject(prompt, slug) }
}

export async function makeZip(files, slug) {
  const zip = new JSZip()
  const root = zip.folder(slug)
  for (const f of files) root.file(f.path, f.content)
  return zip.generateAsync({ type: 'blob' })
}

const TEAM_LABEL = {
  auto: 'auto-routed',
  code: 'team.code',
  brain: 'team.brain',
  vision: 'team.vision',
  design: 'team.design',
}

export function respond(prompt, attachments, team = 'auto') {
  const attachNote = attachments.length
    ? `\n[CONTEXT] ${attachments.length} attachment${attachments.length > 1 ? 's' : ''} received: ${attachments
        .slice(0, 3)
        .map((a) => a.name)
        .join(', ')}${attachments.length > 3 ? '…' : ''}\n`
    : '\n'

  if (isCodingTask(prompt)) {
    const { slug, files } = generateFiles(prompt)
    const fileList = files.map((f) => `- \`${slug}/${f.path}\``).join('\n')
    const text =
      `[ROUTER] intent: code — dispatched to ${TEAM_LABEL[team] || 'team.code'}\n` +
      `[COUNCIL] plan → draft → critique → refine → synthesize ✓\n` +
      `[VERIFY] battery pass — 0 broken imports · 0 placeholder stubs${attachNote}\n` +
      `Here's a working scaffold for your task.\n\n` +
      `**Files generated**\n${fileList}\n\n` +
      `Everything is packaged below — download the zip, unzip it, and run it locally. ` +
      `The README inside has the exact commands.\n\n` +
      `*(demo engine — connect the local VibeAI API for real multi-model runs)*`
    return { text, project: { slug, files } }
  }

  const text =
    `[ROUTER] intent: reasoning — dispatched to ${TEAM_LABEL[team] || 'team.brain'}\n` +
    `[COUNCIL] 5-stage pipeline complete ✓${attachNote}\n` +
    `On the real system this answer would be planned, drafted, critiqued, refined, and ` +
    `synthesized by several free-tier models before you saw a word of it — with the circuit ` +
    `breaker failing over between providers mid-flight if one of them rate-limits.\n\n` +
    `This hosted site runs a simulated engine, because the actual VibeAI API executes code ` +
    `and shell commands and therefore binds to localhost only. Ask a **coding task** to see ` +
    `the full flow — file generation, verifier output, and a downloadable zip of the project.\n\n` +
    `*(demo engine — connect the local VibeAI API for real multi-model runs)*`
  return { text, project: null }
}
